### ISSUE TITLE
Distccd-x86_64 service uses system gcc (/usr/bin/gcc) not the one meant for x86_64 compiling

### ISSUE THREAD

**Issue by jiriks74** [graysky2/crosstool-ng_for_distcc#4] opened 2020-09-30 17:50 UTC
I installed the package, configured the ip's and I get an error:
```
distccd[385] (dcc_job_summary) client: 10.243.12.6:55314 COMPILE_ERROR exit:1 sig:0 core:0 ret:0 time:368ms /usr/bin/gcc drivers/acpi/acpica/evgpe.c
```
My `/usr/lib/systemd/system/distccd-x86_64.service` looks like:
```
[Unit]
Description=Distributed compilation server for C, C++ and Objective-C
Documentation=man:distccd(1)
After=network.target

[Service]
User=distcc
EnvironmentFile=/etc/conf.d/distccd-x86_64
ExecStart=/usr/bin/distccd --no-detach --daemon $DISTCC_ARGS

[Install]
WantedBy=multi-user.target
```
And my `/etc/conf.d/distccd-x86_64` looks like:
```
#
# Parameters to be passed to distccd
#
# You must explicitly add IPs (or subnets) that are allowed to connect,
# using the --allow switch.  See the distccd manpage for more info.
#

PATH=/opt/x-tools86/x86_64-pc-linux-gnu/bin:$PATH
#DISTCC_ARGS="--allow-private --log-file /tmp/distccd-x86_64.log"
DISTCC_ARGS="--allow 10.243.12.0/20 --log-file /tmp/distccd-x86_64.log"
```
The issue is that it uses the system `gcc` not the copmpiler packaged with this tool. I check if the directory and the tool are where they should and they are:
```
$ /opt/x-tools86/x86_64-pc-linux-gnu/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/opt/x-tools86/x86_64-pc-linux-gnu/bin/gcc
COLLECT_LTO_WRAPPER=/opt/x-tools86/x86_64-pc-linux-gnu/bin/../libexec/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /scratch/ct_build/.build/x86_64-pc-linux-gnu/src/gcc/configure --build=armv7l-build_unknown-linux-gnueabihf --host=armv7l-build_unknown-linux-gnueabihf --target=x86_64-pc-linux-gnu --prefix=/scratch/ct_build/x86_64-pc-linux-gnu --with-sysroot=/scratch/ct_build/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot --enable-languages=c,c++ --with-cpu=x86-64 --with-tune=generic --with-pkgversion='crosstool-NG 1.24.0.108_81a85a7' --enable-__cxa_atexit --disable-libmudflap --enable-libgomp --disable-libssp --enable-libquadmath --enable-libquadmath-support --enable-libsanitizer --enable-libmpx --with-gmp=/scratch/ct_build/.build/x86_64-pc-linux-gnu/buildtools --with-mpfr=/scratch/ct_build/.build/x86_64-pc-linux-gnu/buildtools --with-mpc=/scratch/ct_build/.build/x86_64-pc-linux-gnu/buildtools --with-isl=/scratch/ct_build/.build/x86_64-pc-linux-gnu/buildtools --enable-lto --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --enable-threads=posix --enable-target-optspace --with-linker-hash-style=gnu --enable-plugin --disable-nls --disable-multilib --with-local-prefix=/scratch/ct_build/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sysroot --enable-long-long --enable-default-pie --enable-default-ssp
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (crosstool-NG 1.24.0.108_81a85a7)
```

**Comment by graysky2** [comment] 2020-09-30 19:51
> I installed the package, configured the ip's and I get an error:

I assume you installed [this](https://aur.archlinux.org/packages/distccd-x86_64/) package on your Arch ARM device?  Regular distcc is required on your x86_64 device.

For me, using a similar configuration to the one you posted above works as expected.  I did not modify `/etc/conf.d/distccd-x86_64` as you did.  I believe the `--allow private` covers that IP range.

> From distccd manpage, Allow private networks (10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12, and 127.0.0.0/8).

**Comment by jiriks74** [comment] 2020-09-30 21:27
I installed have the package you sent installed. I tried it with the original `/etc/conf.d/distccd-x86_64`, still not working. Works only after manually deleting `/usr/bin/gcc` and `ln -s /opt/x-tools86/x86_64-pc-linux-gnu/bin /usr/bin/gcc` whic is not good as that breaks functionality of compilation on the raspberry. The package I try to compile is linux kernel the exact package is `linux-xanmod` and `linux-xanmod-headers`.

**Comment by graysky2** [comment] 2020-09-30 22:20
Arch x86_64 and Arch ARM?  How are you compiling?  Note there is a bug with kernel compilation with distcc... work around: https://wiki.archlinux.org/index.php/Distcc#Quirks_compiling_the_Arch_Linux_kernel_package

**Comment by jiriks74** [comment] 2020-10-01 10:12
I have my pi with the package you provide. I setup the distccd server and on my PC I use distcc to compile the kernel. The PC's side is ok, as if I manually link the compiler to /usr/bin/gcc everything works fine. From what could I see, it may be that the distccd server is told to use /usr/bin/gcc explicitly. I think I saw it in logs. 
```
...
distccd[3475] (dcc_check_client) connection from 10.243.12.6:56778
distccd[3475] (check_address_inet) match client 0x60cf30a, value 0xcf30a, mask 0xf0ffff
distccd[3475] (dcc_r_token_int) got DIST00000001
distccd[3475] (dcc_r_token_int) got ARGC0000004b
distccd[3475] (dcc_r_argv) reading 75 arguments from job submission
distccd[3475] (dcc_r_token_int) got ARGV0000000c
distccd[3475] (dcc_r_token_string) got '/usr/bin/gcc'
distccd[3475] (dcc_r_argv) argv[0] = "/usr/bin/gcc"
...
```

**Comment by graysky2** [comment] 2020-10-01 12:41
There should be no need to manually symlink.  Did you see that wiki note about kernel compilation via distcc?

**Comment by jiriks74** [comment] 2020-10-05 08:34
I did. I think the issue is that the client sends absolute path to compiler instead of relative (`/usr/bin/gcc` instead of `gcc`). How can I make sure it sends relative path only?

**Comment by graysky2** [comment] 2020-10-05 11:05
I cannot reproduce this.

**Comment by jiriks74** [comment] 2020-10-09 19:20
What distribution is your client running?

**Comment by graysky2** [comment] 2020-10-09 22:14
Client runs Arch/volunteers run Arch ARM.

**Comment by graysky2** [comment] 2022-04-05 11:05
Cannot reproduce, closing.  Feel free to request a reopen if there are new details you can provide.

**Closed as completed by graysky2** 2022-04-05 11:05 UTC
